# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('has_paied', models.BooleanField(default=False)),
                ('game_progress', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignedMaps',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=32)),
                ('remarks', models.CharField(max_length=1000)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DesignedMaps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameLevels',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map', models.CharField(max_length=1000)),
                ('level_three_steps', models.SmallIntegerField()),
                ('level_two_steps', models.SmallIntegerField()),
                ('tips', models.CharField(max_length=1000)),
                ('goal', models.CharField(max_length=1000)),
            ],
        ),
    ]
