# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelevels',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='gamelevels',
            name='level_three_steps',
        ),
        migrations.RemoveField(
            model_name='gamelevels',
            name='level_two_steps',
        ),
        migrations.AddField(
            model_name='gamelevels',
            name='codes',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='gamelevels',
            name='mode',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='gamelevels',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='gamelevels',
            name='map',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamelevels',
            name='map_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamelevels',
            name='tips',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
