"""
Django settings for doublegame project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=t^-i_i7sm$n9+7pt-=!gmd&4hn&+060i0t*0%uo4pw2u&66@s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'gunicorn'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'doublegame.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'doublegame.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'doublegame',
        'USER': 'root',
        'PASSWORD': 'vagrant',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'api.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# 电子邮件配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 主机
EMAIL_HOST = 'smtp.aliyun.com'
# 端口
EMAIL_PORT = 25
# 验证邮箱
EMAIL_HOST_USER = 'sagualiazao@aliyun.com'
# 密码
EMAIL_HOST_PASSWORD = 'sagua_liazao'
# 是否使用https
# EMAIL_USE_TLS = True
# 发件人
EMAIL_FROM = "仨瓜俩枣小组"



# 跨域访问配置
# CORS_ORIGIN_ALLOW_ALL = True



# 设置服务器session
# 要让服务器的session生效,只需要在前端的fetch中加上:  credentials: 'include',
# 设置cookie发送,与XHR2的withCredentials类似

# Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
SESSION_COOKIE_NAME = 'sagualiazao'
# Session的cookie保存的路径（默认）
# SESSION_COOKIE_PATH = '/'
# Session的cookie保存的域名（默认）
# SESSION_COOKIE_DOMAIN = None
# 是否Https传输cookie（默认）
# SESSION_COOKIE_SECURE = False
# 是否Session的cookie只支持http传输（默认）
# SESSION_COOKIE_HTTPONLY = True
# Session的cookie失效日期（2周）（默认）
# SESSION_COOKIE_AGE = 1209600
# 是否关闭浏览器使得Session过期（默认）
# 默认值为false,浏览器会生成一个名为csrf_token的cookie,用来记录登录数据
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
